version: '3.9'

services:
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: sobes_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

















#  app:
#    image: openjdk:17
#    container_name: app_container
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/sobes_db
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: user
#      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
#      SPRING_SERVER_PORT: 1111
#    ports:
#     - "1111:1111"
#    depends_on:
#      - postgres_db