name: CI Pipeline
on: [push]
jobs:
  build:
    name: Build and Test with Docker Compose and Maven
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5436:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: user
          POSTGRES_DB: sobes_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: sudo apt-get install docker-compose

      - name: Build Docker Images
        run: docker-compose -f docker-compose.yml build

      - name: Run Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for PostgreSQL to be ready
        run: docker-compose -f docker-compose.yml exec -T postgres_db /bin/sh -c 'until pg_isready -U user; do sleep 1; done'

      - name: Run Tests
        run: mvn test
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5436/sobes_db
          SPRING_DATASOURCE_USERNAME: user
          SPRING_DATASOURCE_PASSWORD: user

      - name: Stop and Remove Docker Containers
        if: always()
        run: docker-compose -f docker-compose.yml down

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports