name: CI Pipeline
on: [push]
jobs:
  build:
    name: Build and Test with Docker Compose and Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt-openjdk'

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run Tests
        run: |
          docker-compose -f docker-compose.yml exec -T app mvn test

      - name: Stop and Remove Docker Containers
        if: always()
        run: |
          docker-compose -f docker-compose.yml down

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports
